/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddCommentArgs = IDL.Record({
  'content' : IDL.Text,
  'ticketId' : IDL.Nat,
  'author' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Platform = IDL.Variant({
  'Freshworks' : IDL.Null,
  'OneSpan' : IDL.Null,
  'ObserveAI' : IDL.Null,
});
export const HelpTopic = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'createdTime' : IDL.Int,
  'platform' : Platform,
  'modifiedTime' : IDL.Int,
  'topicName' : IDL.Text,
});
export const TicketStatus = IDL.Variant({
  'Submitted' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const Brand = IDL.Variant({
  'ALPA' : IDL.Null,
  'VirtualStore' : IDL.Null,
  'AMAXCA' : IDL.Null,
  'AMAXTX' : IDL.Null,
});
export const TicketPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'empty' : IDL.Null,
  'medium' : IDL.Null,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'freshworksEmail' : IDL.Opt(IDL.Text),
  'issueDescription' : IDL.Text,
  'displayName' : IDL.Text,
  'officeName' : IDL.Text,
  'agentName' : IDL.Text,
  'platform' : Platform,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'submissionTime' : IDL.Int,
  'brand' : Brand,
  'priority' : TicketPriority,
  'comments' : IDL.Vec(Comment),
  'policyNumber' : IDL.Opt(IDL.Text),
  'extension' : IDL.Opt(IDL.Text),
  'attachments' : IDL.Vec(ExternalBlob),
});
export const Granularity = IDL.Variant({
  'day' : IDL.Null,
  'month' : IDL.Null,
  'week' : IDL.Null,
});
export const AnalyticsRequest = IDL.Record({
  'startTime' : IDL.Int,
  'endTime' : IDL.Int,
  'granularity' : Granularity,
});
export const PeriodCounts = IDL.Record({
  'total' : IDL.Nat,
  'freshworks' : IDL.Nat,
  'observeAI' : IDL.Nat,
  'onespan' : IDL.Nat,
});
export const TicketAnalytics = IDL.Record({
  'periods' : IDL.Vec(IDL.Tuple(IDL.Text, PeriodCounts)),
});
export const GetTicketsArgs = IDL.Record({
  'endDate' : IDL.Opt(IDL.Int),
  'brandFilter' : IDL.Opt(Brand),
  'priorityFilter' : IDL.Opt(TicketPriority),
  'platformFilter' : IDL.Opt(Platform),
  'statusFilter' : IDL.Opt(TicketStatus),
  'startDate' : IDL.Opt(IDL.Int),
});
export const CreateTicketArgs = IDL.Record({
  'freshworksEmail' : IDL.Opt(IDL.Text),
  'issueDescription' : IDL.Text,
  'officeName' : IDL.Text,
  'agentName' : IDL.Text,
  'platform' : Platform,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'brand' : Brand,
  'policyNumber' : IDL.Opt(IDL.Text),
  'extension' : IDL.Opt(IDL.Text),
  'attachments' : IDL.Vec(ExternalBlob),
});
export const UpdateTicketPriorityArgs = IDL.Record({
  'ticketId' : IDL.Nat,
  'newPriority' : TicketPriority,
});
export const UpdateStatusArgs = IDL.Record({
  'ticketId' : IDL.Nat,
  'newStatus' : TicketStatus,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([AddCommentArgs], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHelpTopic' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHelpTopics' : IDL.Func([], [IDL.Vec(HelpTopic)], ['query']),
  'getHelpTopicsDraft' : IDL.Func([], [IDL.Vec(HelpTopic)], ['query']),
  'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(Ticket)], ['query']),
  'getTicketAnalytics' : IDL.Func(
      [AnalyticsRequest],
      [TicketAnalytics],
      ['query'],
    ),
  'getTickets' : IDL.Func([GetTicketsArgs], [IDL.Vec(Ticket)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishHelpContent' : IDL.Func([], [], []),
  'saveHelpTopic' : IDL.Func([HelpTopic], [IDL.Nat], []),
  'searchTickets' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
  'submitTicket' : IDL.Func([CreateTicketArgs], [IDL.Nat], []),
  'updateTicketPriority' : IDL.Func([UpdateTicketPriorityArgs], [], []),
  'updateTicketStatus' : IDL.Func([UpdateStatusArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddCommentArgs = IDL.Record({
    'content' : IDL.Text,
    'ticketId' : IDL.Nat,
    'author' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'Freshworks' : IDL.Null,
    'OneSpan' : IDL.Null,
    'ObserveAI' : IDL.Null,
  });
  const HelpTopic = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'createdTime' : IDL.Int,
    'platform' : Platform,
    'modifiedTime' : IDL.Int,
    'topicName' : IDL.Text,
  });
  const TicketStatus = IDL.Variant({
    'Submitted' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const Brand = IDL.Variant({
    'ALPA' : IDL.Null,
    'VirtualStore' : IDL.Null,
    'AMAXCA' : IDL.Null,
    'AMAXTX' : IDL.Null,
  });
  const TicketPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'empty' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'freshworksEmail' : IDL.Opt(IDL.Text),
    'issueDescription' : IDL.Text,
    'displayName' : IDL.Text,
    'officeName' : IDL.Text,
    'agentName' : IDL.Text,
    'platform' : Platform,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'submissionTime' : IDL.Int,
    'brand' : Brand,
    'priority' : TicketPriority,
    'comments' : IDL.Vec(Comment),
    'policyNumber' : IDL.Opt(IDL.Text),
    'extension' : IDL.Opt(IDL.Text),
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const Granularity = IDL.Variant({
    'day' : IDL.Null,
    'month' : IDL.Null,
    'week' : IDL.Null,
  });
  const AnalyticsRequest = IDL.Record({
    'startTime' : IDL.Int,
    'endTime' : IDL.Int,
    'granularity' : Granularity,
  });
  const PeriodCounts = IDL.Record({
    'total' : IDL.Nat,
    'freshworks' : IDL.Nat,
    'observeAI' : IDL.Nat,
    'onespan' : IDL.Nat,
  });
  const TicketAnalytics = IDL.Record({
    'periods' : IDL.Vec(IDL.Tuple(IDL.Text, PeriodCounts)),
  });
  const GetTicketsArgs = IDL.Record({
    'endDate' : IDL.Opt(IDL.Int),
    'brandFilter' : IDL.Opt(Brand),
    'priorityFilter' : IDL.Opt(TicketPriority),
    'platformFilter' : IDL.Opt(Platform),
    'statusFilter' : IDL.Opt(TicketStatus),
    'startDate' : IDL.Opt(IDL.Int),
  });
  const CreateTicketArgs = IDL.Record({
    'freshworksEmail' : IDL.Opt(IDL.Text),
    'issueDescription' : IDL.Text,
    'officeName' : IDL.Text,
    'agentName' : IDL.Text,
    'platform' : Platform,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'brand' : Brand,
    'policyNumber' : IDL.Opt(IDL.Text),
    'extension' : IDL.Opt(IDL.Text),
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const UpdateTicketPriorityArgs = IDL.Record({
    'ticketId' : IDL.Nat,
    'newPriority' : TicketPriority,
  });
  const UpdateStatusArgs = IDL.Record({
    'ticketId' : IDL.Nat,
    'newStatus' : TicketStatus,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([AddCommentArgs], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHelpTopic' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHelpTopics' : IDL.Func([], [IDL.Vec(HelpTopic)], ['query']),
    'getHelpTopicsDraft' : IDL.Func([], [IDL.Vec(HelpTopic)], ['query']),
    'getTicket' : IDL.Func([IDL.Nat], [IDL.Opt(Ticket)], ['query']),
    'getTicketAnalytics' : IDL.Func(
        [AnalyticsRequest],
        [TicketAnalytics],
        ['query'],
      ),
    'getTickets' : IDL.Func([GetTicketsArgs], [IDL.Vec(Ticket)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishHelpContent' : IDL.Func([], [], []),
    'saveHelpTopic' : IDL.Func([HelpTopic], [IDL.Nat], []),
    'searchTickets' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
    'submitTicket' : IDL.Func([CreateTicketArgs], [IDL.Nat], []),
    'updateTicketPriority' : IDL.Func([UpdateTicketPriorityArgs], [], []),
    'updateTicketStatus' : IDL.Func([UpdateStatusArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };