/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCommentArgs {
  'content' : string,
  'ticketId' : bigint,
  'author' : string,
}
export interface AnalyticsRequest {
  'startTime' : bigint,
  'endTime' : bigint,
  'granularity' : Granularity,
}
export type Brand = { 'ALPA' : null } |
  { 'VirtualStore' : null } |
  { 'AMAXCA' : null } |
  { 'AMAXTX' : null };
export interface Comment {
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface CreateTicketArgs {
  'freshworksEmail' : [] | [string],
  'issueDescription' : string,
  'officeName' : string,
  'agentName' : string,
  'platform' : Platform,
  'email' : string,
  'employeeId' : string,
  'brand' : Brand,
  'policyNumber' : [] | [string],
  'extension' : [] | [string],
  'attachments' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface GetTicketsArgs {
  'endDate' : [] | [bigint],
  'brandFilter' : [] | [Brand],
  'priorityFilter' : [] | [TicketPriority],
  'platformFilter' : [] | [Platform],
  'statusFilter' : [] | [TicketStatus],
  'startDate' : [] | [bigint],
}
export type Granularity = { 'day' : null } |
  { 'month' : null } |
  { 'week' : null };
export interface HelpTopic {
  'id' : bigint,
  'explanation' : string,
  'createdTime' : bigint,
  'platform' : Platform,
  'modifiedTime' : bigint,
  'topicName' : string,
}
export interface PeriodCounts {
  'total' : bigint,
  'freshworks' : bigint,
  'observeAI' : bigint,
  'onespan' : bigint,
}
export type Platform = { 'Freshworks' : null } |
  { 'OneSpan' : null } |
  { 'ObserveAI' : null };
export interface Ticket {
  'id' : bigint,
  'status' : TicketStatus,
  'freshworksEmail' : [] | [string],
  'issueDescription' : string,
  'displayName' : string,
  'officeName' : string,
  'agentName' : string,
  'platform' : Platform,
  'email' : string,
  'employeeId' : string,
  'submissionTime' : bigint,
  'brand' : Brand,
  'priority' : TicketPriority,
  'comments' : Array<Comment>,
  'policyNumber' : [] | [string],
  'extension' : [] | [string],
  'attachments' : Array<ExternalBlob>,
}
export interface TicketAnalytics { 'periods' : Array<[string, PeriodCounts]> }
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'empty' : null } |
  { 'medium' : null };
export type TicketStatus = { 'Submitted' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export interface UpdateStatusArgs {
  'ticketId' : bigint,
  'newStatus' : TicketStatus,
}
export interface UpdateTicketPriorityArgs {
  'ticketId' : bigint,
  'newPriority' : TicketPriority,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[AddCommentArgs], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteHelpTopic' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHelpTopics' : ActorMethod<[], Array<HelpTopic>>,
  'getHelpTopicsDraft' : ActorMethod<[], Array<HelpTopic>>,
  'getTicket' : ActorMethod<[bigint], [] | [Ticket]>,
  'getTicketAnalytics' : ActorMethod<[AnalyticsRequest], TicketAnalytics>,
  'getTickets' : ActorMethod<[GetTicketsArgs], Array<Ticket>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishHelpContent' : ActorMethod<[], undefined>,
  'saveHelpTopic' : ActorMethod<[HelpTopic], bigint>,
  'searchTickets' : ActorMethod<[string], Array<Ticket>>,
  'submitTicket' : ActorMethod<[CreateTicketArgs], bigint>,
  'updateTicketPriority' : ActorMethod<[UpdateTicketPriorityArgs], undefined>,
  'updateTicketStatus' : ActorMethod<[UpdateStatusArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];