/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CreateTicketArgs {
    freshworksEmail?: string;
    issueDescription: string;
    officeName: string;
    agentName: string;
    platform: Platform;
    email: string;
    employeeId: string;
    brand: Brand;
    policyNumber?: string;
    extension?: string;
    attachments: Array<ExternalBlob>;
}
export interface Comment {
    content: string;
    author: string;
    timestamp: bigint;
}
export interface UpdateStatusArgs {
    ticketId: bigint;
    newStatus: TicketStatus;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UpdateTicketPriorityArgs {
    ticketId: bigint;
    newPriority: TicketPriority;
}
export interface AddCommentArgs {
    content: string;
    ticketId: bigint;
    author: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TicketAnalytics {
    periods: Array<[string, PeriodCounts]>;
}
export interface AnalyticsRequest {
    startTime: bigint;
    endTime: bigint;
    granularity: Granularity;
}
export interface GetTicketsArgs {
    endDate?: bigint;
    brandFilter?: Brand;
    priorityFilter?: TicketPriority;
    platformFilter?: Platform;
    statusFilter?: TicketStatus;
    startDate?: bigint;
}
export interface Ticket {
    id: bigint;
    status: TicketStatus;
    freshworksEmail?: string;
    issueDescription: string;
    displayName: string;
    officeName: string;
    agentName: string;
    platform: Platform;
    email: string;
    employeeId: string;
    submissionTime: bigint;
    brand: Brand;
    priority: TicketPriority;
    comments: Array<Comment>;
    policyNumber?: string;
    extension?: string;
    attachments: Array<ExternalBlob>;
}
export interface PeriodCounts {
    total: bigint;
    freshworks: bigint;
    observeAI: bigint;
    onespan: bigint;
}
export interface HelpTopic {
    id: bigint;
    explanation: string;
    createdTime: bigint;
    platform: Platform;
    modifiedTime: bigint;
    topicName: string;
}
export enum Brand {
    ALPA = "ALPA",
    VirtualStore = "VirtualStore",
    AMAXCA = "AMAXCA",
    AMAXTX = "AMAXTX"
}
export enum Granularity {
    day = "day",
    month = "month",
    week = "week"
}
export enum Platform {
    Freshworks = "Freshworks",
    OneSpan = "OneSpan",
    ObserveAI = "ObserveAI"
}
export enum TicketPriority {
    low = "low",
    high = "high",
    empty = "empty",
    medium = "medium"
}
export enum TicketStatus {
    Submitted = "Submitted",
    InProgress = "InProgress",
    Resolved = "Resolved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(args: AddCommentArgs): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteHelpTopic(topicId: bigint): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getHelpTopics(): Promise<Array<HelpTopic>>;
    getHelpTopicsDraft(): Promise<Array<HelpTopic>>;
    getTicket(ticketId: bigint): Promise<Ticket | null>;
    getTicketAnalytics(req: AnalyticsRequest): Promise<TicketAnalytics>;
    getTickets(args: GetTicketsArgs): Promise<Array<Ticket>>;
    isCallerAdmin(): Promise<boolean>;
    publishHelpContent(): Promise<void>;
    saveHelpTopic(topic: HelpTopic): Promise<bigint>;
    searchTickets(searchTerm: string): Promise<Array<Ticket>>;
    submitTicket(args: CreateTicketArgs): Promise<bigint>;
    updateTicketPriority(args: UpdateTicketPriorityArgs): Promise<void>;
    updateTicketStatus(args: UpdateStatusArgs): Promise<void>;
}
import type { AnalyticsRequest as _AnalyticsRequest, Brand as _Brand, Comment as _Comment, CreateTicketArgs as _CreateTicketArgs, ExternalBlob as _ExternalBlob, GetTicketsArgs as _GetTicketsArgs, Granularity as _Granularity, HelpTopic as _HelpTopic, Platform as _Platform, Ticket as _Ticket, TicketPriority as _TicketPriority, TicketStatus as _TicketStatus, UpdateStatusArgs as _UpdateStatusArgs, UpdateTicketPriorityArgs as _UpdateTicketPriorityArgs, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: AddCommentArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteHelpTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHelpTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHelpTopic(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelpTopics(): Promise<Array<HelpTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpTopics();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpTopics();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelpTopicsDraft(): Promise<Array<HelpTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpTopicsDraft();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpTopicsDraft();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicket(arg0: bigint): Promise<Ticket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicket(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicket(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketAnalytics(arg0: AnalyticsRequest): Promise<TicketAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketAnalytics(to_candid_AnalyticsRequest_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketAnalytics(to_candid_AnalyticsRequest_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTickets(arg0: GetTicketsArgs): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTickets(to_candid_GetTicketsArgs_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTickets(to_candid_GetTicketsArgs_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishHelpContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishHelpContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishHelpContent();
            return result;
        }
    }
    async saveHelpTopic(arg0: HelpTopic): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHelpTopic(to_candid_HelpTopic_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHelpTopic(to_candid_HelpTopic_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTickets(arg0: string): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTickets(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTickets(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTicket(arg0: CreateTicketArgs): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTicket(await to_candid_CreateTicketArgs_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTicket(await to_candid_CreateTicketArgs_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTicketPriority(arg0: UpdateTicketPriorityArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketPriority(to_candid_UpdateTicketPriorityArgs_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketPriority(to_candid_UpdateTicketPriorityArgs_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTicketStatus(arg0: UpdateStatusArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(to_candid_UpdateStatusArgs_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(to_candid_UpdateStatusArgs_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Brand_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Brand): Brand {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HelpTopic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HelpTopic): HelpTopic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TicketPriority_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketPriority): TicketPriority {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_Ticket_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Promise<Ticket> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ticket]): Promise<Ticket | null> {
    return value.length === 0 ? null : await from_candid_Ticket_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: string;
    createdTime: bigint;
    platform: _Platform;
    modifiedTime: bigint;
    topicName: string;
}): {
    id: bigint;
    explanation: string;
    createdTime: bigint;
    platform: Platform;
    modifiedTime: bigint;
    topicName: string;
} {
    return {
        id: value.id,
        explanation: value.explanation,
        createdTime: value.createdTime,
        platform: from_candid_Platform_n15(_uploadFile, _downloadFile, value.platform),
        modifiedTime: value.modifiedTime,
        topicName: value.topicName
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TicketStatus;
    freshworksEmail: [] | [string];
    issueDescription: string;
    displayName: string;
    officeName: string;
    agentName: string;
    platform: _Platform;
    email: string;
    employeeId: string;
    submissionTime: bigint;
    brand: _Brand;
    priority: _TicketPriority;
    comments: Array<_Comment>;
    policyNumber: [] | [string];
    extension: [] | [string];
    attachments: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    status: TicketStatus;
    freshworksEmail?: string;
    issueDescription: string;
    displayName: string;
    officeName: string;
    agentName: string;
    platform: Platform;
    email: string;
    employeeId: string;
    submissionTime: bigint;
    brand: Brand;
    priority: TicketPriority;
    comments: Array<Comment>;
    policyNumber?: string;
    extension?: string;
    attachments: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n20(_uploadFile, _downloadFile, value.status),
        freshworksEmail: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.freshworksEmail)),
        issueDescription: value.issueDescription,
        displayName: value.displayName,
        officeName: value.officeName,
        agentName: value.agentName,
        platform: from_candid_Platform_n15(_uploadFile, _downloadFile, value.platform),
        email: value.email,
        employeeId: value.employeeId,
        submissionTime: value.submissionTime,
        brand: from_candid_Brand_n23(_uploadFile, _downloadFile, value.brand),
        priority: from_candid_TicketPriority_n25(_uploadFile, _downloadFile, value.priority),
        comments: value.comments,
        policyNumber: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.policyNumber)),
        extension: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.extension)),
        attachments: await from_candid_vec_n27(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Freshworks: null;
} | {
    OneSpan: null;
} | {
    ObserveAI: null;
}): Platform {
    return "Freshworks" in value ? Platform.Freshworks : "OneSpan" in value ? Platform.OneSpan : "ObserveAI" in value ? Platform.ObserveAI : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Submitted: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
}): TicketStatus {
    return "Submitted" in value ? TicketStatus.Submitted : "InProgress" in value ? TicketStatus.InProgress : "Resolved" in value ? TicketStatus.Resolved : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ALPA: null;
} | {
    VirtualStore: null;
} | {
    AMAXCA: null;
} | {
    AMAXTX: null;
}): Brand {
    return "ALPA" in value ? Brand.ALPA : "VirtualStore" in value ? Brand.VirtualStore : "AMAXCA" in value ? Brand.AMAXCA : "AMAXTX" in value ? Brand.AMAXTX : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    empty: null;
} | {
    medium: null;
}): TicketPriority {
    return "low" in value ? TicketPriority.low : "high" in value ? TicketPriority.high : "empty" in value ? TicketPriority.empty : "medium" in value ? TicketPriority.medium : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HelpTopic>): Array<HelpTopic> {
    return value.map((x)=>from_candid_HelpTopic_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Promise<Array<Ticket>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Ticket_n18(_uploadFile, _downloadFile, x)));
}
function to_candid_AnalyticsRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsRequest): _AnalyticsRequest {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Brand_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Brand): _Brand {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateTicketArgs_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTicketArgs): Promise<_CreateTicketArgs> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GetTicketsArgs_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GetTicketsArgs): _GetTicketsArgs {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Granularity_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Granularity): _Granularity {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_HelpTopic_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HelpTopic): _HelpTopic {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_TicketPriority_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): _TicketPriority {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStatusArgs_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusArgs): _UpdateStatusArgs {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTicketPriorityArgs_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTicketPriorityArgs): _UpdateTicketPriorityArgs {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    endTime: bigint;
    granularity: Granularity;
}): {
    startTime: bigint;
    endTime: bigint;
    granularity: _Granularity;
} {
    return {
        startTime: value.startTime,
        endTime: value.endTime,
        granularity: to_candid_Granularity_n31(_uploadFile, _downloadFile, value.granularity)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: bigint;
    brandFilter?: Brand;
    priorityFilter?: TicketPriority;
    platformFilter?: Platform;
    statusFilter?: TicketStatus;
    startDate?: bigint;
}): {
    endDate: [] | [bigint];
    brandFilter: [] | [_Brand];
    priorityFilter: [] | [_TicketPriority];
    platformFilter: [] | [_Platform];
    statusFilter: [] | [_TicketStatus];
    startDate: [] | [bigint];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        brandFilter: value.brandFilter ? candid_some(to_candid_Brand_n35(_uploadFile, _downloadFile, value.brandFilter)) : candid_none(),
        priorityFilter: value.priorityFilter ? candid_some(to_candid_TicketPriority_n37(_uploadFile, _downloadFile, value.priorityFilter)) : candid_none(),
        platformFilter: value.platformFilter ? candid_some(to_candid_Platform_n39(_uploadFile, _downloadFile, value.platformFilter)) : candid_none(),
        statusFilter: value.statusFilter ? candid_some(to_candid_TicketStatus_n41(_uploadFile, _downloadFile, value.statusFilter)) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: string;
    createdTime: bigint;
    platform: Platform;
    modifiedTime: bigint;
    topicName: string;
}): {
    id: bigint;
    explanation: string;
    createdTime: bigint;
    platform: _Platform;
    modifiedTime: bigint;
    topicName: string;
} {
    return {
        id: value.id,
        explanation: value.explanation,
        createdTime: value.createdTime,
        platform: to_candid_Platform_n39(_uploadFile, _downloadFile, value.platform),
        modifiedTime: value.modifiedTime,
        topicName: value.topicName
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freshworksEmail?: string;
    issueDescription: string;
    officeName: string;
    agentName: string;
    platform: Platform;
    email: string;
    employeeId: string;
    brand: Brand;
    policyNumber?: string;
    extension?: string;
    attachments: Array<ExternalBlob>;
}): Promise<{
    freshworksEmail: [] | [string];
    issueDescription: string;
    officeName: string;
    agentName: string;
    platform: _Platform;
    email: string;
    employeeId: string;
    brand: _Brand;
    policyNumber: [] | [string];
    extension: [] | [string];
    attachments: Array<_ExternalBlob>;
}> {
    return {
        freshworksEmail: value.freshworksEmail ? candid_some(value.freshworksEmail) : candid_none(),
        issueDescription: value.issueDescription,
        officeName: value.officeName,
        agentName: value.agentName,
        platform: to_candid_Platform_n39(_uploadFile, _downloadFile, value.platform),
        email: value.email,
        employeeId: value.employeeId,
        brand: to_candid_Brand_n35(_uploadFile, _downloadFile, value.brand),
        policyNumber: value.policyNumber ? candid_some(value.policyNumber) : candid_none(),
        extension: value.extension ? candid_some(value.extension) : candid_none(),
        attachments: await to_candid_vec_n48(_uploadFile, _downloadFile, value.attachments)
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticketId: bigint;
    newPriority: TicketPriority;
}): {
    ticketId: bigint;
    newPriority: _TicketPriority;
} {
    return {
        ticketId: value.ticketId,
        newPriority: to_candid_TicketPriority_n37(_uploadFile, _downloadFile, value.newPriority)
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticketId: bigint;
    newStatus: TicketStatus;
}): {
    ticketId: bigint;
    newStatus: _TicketStatus;
} {
    return {
        ticketId: value.ticketId,
        newStatus: to_candid_TicketStatus_n41(_uploadFile, _downloadFile, value.newStatus)
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Granularity): {
    day: null;
} | {
    month: null;
} | {
    week: null;
} {
    return value == Granularity.day ? {
        day: null
    } : value == Granularity.month ? {
        month: null
    } : value == Granularity.week ? {
        week: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Brand): {
    ALPA: null;
} | {
    VirtualStore: null;
} | {
    AMAXCA: null;
} | {
    AMAXTX: null;
} {
    return value == Brand.ALPA ? {
        ALPA: null
    } : value == Brand.VirtualStore ? {
        VirtualStore: null
    } : value == Brand.AMAXCA ? {
        AMAXCA: null
    } : value == Brand.AMAXTX ? {
        AMAXTX: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): {
    low: null;
} | {
    high: null;
} | {
    empty: null;
} | {
    medium: null;
} {
    return value == TicketPriority.low ? {
        low: null
    } : value == TicketPriority.high ? {
        high: null
    } : value == TicketPriority.empty ? {
        empty: null
    } : value == TicketPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    Freshworks: null;
} | {
    OneSpan: null;
} | {
    ObserveAI: null;
} {
    return value == Platform.Freshworks ? {
        Freshworks: null
    } : value == Platform.OneSpan ? {
        OneSpan: null
    } : value == Platform.ObserveAI ? {
        ObserveAI: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    Submitted: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
} {
    return value == TicketStatus.Submitted ? {
        Submitted: null
    } : value == TicketStatus.InProgress ? {
        InProgress: null
    } : value == TicketStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n49(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
